class OperationWithUsers:
    def __int__(self, file):
        ...

    def append_in_list(self, oper):
        ...

    def check_data_time(self, oper):
        ...


    def enter_user_info(self, end_list):
        ...